exclude: 'cookiecutter\.repo_name'
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/psf/black
    rev: "21.8b0"
    hooks:
      - id: black
        language_version: python3.10 # Should be a command that runs python3.6+
        args: ["-t", "py39"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.25.0"
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
